using System.Collections.Concurrent;
using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;
using System.Data.Common;
using Chess.Shared;

var port=int.TryParse(Environment.GetEnvironmentVariable("CHESS_PORT"),out var p)?p:5050;
var server=new ChessServer(port); await server.RunAsync();

sealed class ChessServer(int port)
{
    private readonly TcpListener listener=new(IPAddress.Any,port);
    private readonly ConcurrentDictionary<string,Client> online=new(StringComparer.OrdinalIgnoreCase);
    private readonly ConcurrentDictionary<string,Game> games=new();
    private readonly ConcurrentQueue<Client> waiting=new();
    public async Task RunAsync(){await InitializeDatabase();listener.Start();Console.WriteLine($"Online Chess TCP server listening on 0.0.0.0:{port}");while(true){var tcp=await listener.AcceptTcpClientAsync();_ = Task.Run(()=>Handle(tcp));}}
    private async Task Handle(TcpClient tcp)
    {
        Client? client=null;
        try { using var reader=new StreamReader(tcp.GetStream(),Encoding.UTF8); using var writer=new StreamWriter(tcp.GetStream(),new UTF8Encoding(false)){AutoFlush=true};
            while(tcp.Connected){var line=await reader.ReadLineAsync();if(line==null)break;Packet? req;try{req=Wire.Decode(line);}catch{await writer.WriteLineAsync(Wire.Encode(new Packet{Type="ERROR",Error="INVALID_JSON"}));continue;}if(req==null)continue;
                async Task Send(Packet x)=>await writer.WriteLineAsync(Wire.Encode(x));
                switch(req.Type){
                    case "REGISTER": {if(string.IsNullOrWhiteSpace(req.Username)||req.Username.Length<3||string.IsNullOrWhiteSpace(req.Password)||req.Password.Length<8){await Send(Packet.Reply(req,false,"INVALID_INPUT"));break;}if(!await RegisterUser(req.Username,req.Password,req.DisplayName??req.Username)){await Send(Packet.Reply(req,false,"USERNAME_TAKEN"));break;}client=new(req.Username,writer);online[req.Username]=client;var res=Packet.Reply(req,true);res.Username=req.Username;await Send(res);break;}
                    case "LOGIN": {if(string.IsNullOrWhiteSpace(req.Username)||string.IsNullOrWhiteSpace(req.Password)){await Send(Packet.Reply(req,false,"INVALID_CREDENTIALS"));break;} if(!await CheckUser(req.Username,req.Password)){await Send(Packet.Reply(req,false,"INVALID_CREDENTIALS"));break;}if(online.ContainsKey(req.Username)){await Send(Packet.Reply(req,false,"ALREADY_ONLINE"));break;}client=new(req.Username,writer);online[req.Username]=client;var res=Packet.Reply(req,true);res.Username=req.Username;await Send(res);break;}
                    case "GET_ONLINE_PLAYERS": {var r=Packet.Reply(req,true);r.Players=online.Keys.Where(n=>n!=client?.Name).Order().ToList();await Send(r);break;}
                    case "JOIN_MATCHMAKING": {if(client==null){await Send(Packet.Reply(req,false,"AUTH_REQUIRED"));break;}if(!waiting.TryDequeue(out var opponent)){waiting.Enqueue(client);await Send(Packet.Reply(req,true));break;}if(opponent.Name==client.Name){waiting.Enqueue(client);await Send(Packet.Reply(req,true));break;}var id=Guid.NewGuid().ToString();var game=new Game(id,client,opponent);games[id]=game;await SaveGame(game);await Send(new Packet{Type="MATCH_FOUND",Success=true,GameId=id,Opponent=opponent.Name,Board=game.Board.Serialize(),Turn="w",Result="white"});await opponent.Send(new Packet{Type="MATCH_FOUND",Success=true,GameId=id,Opponent=client.Name,Board=game.Board.Serialize(),Turn="w",Result="black"});break;}
                    case "MOVE": {if(!FindGame(req,client,out var g)){await Send(Packet.Reply(req,false,"GAME_NOT_FOUND"));break;}if(g.Board.Turn!=(client==g.White?'w':'b')){await Send(Packet.Reply(req,false,"NOT_YOUR_TURN"));break;}if(!g.Board.Move(req.From,req.To,req.Promotion,out var state)){await Send(Packet.Reply(req,false,"ILLEGAL_MOVE"));break;}await SaveMove(g.Id,req.From??"",req.To??"");var packet=new Packet{Type="GAME_STATE",Success=true,GameId=g.Id,Board=g.Board.Serialize(),Turn=g.Board.Turn.ToString(),Result=state};await g.White.Send(packet);await g.Black.Send(packet);if(state is "Checkmate" or "Stalemate"){g.Result=state;await FinishGame(g,state);games.TryRemove(g.Id,out _);}break;}
                    case "GET_HISTORY": {var r=Packet.Reply(req,true);r.Items=await History(client?.Name??"");await Send(r);break;}
                    case "GET_LEADERBOARD": {var r=Packet.Reply(req,true);r.Items=await Leaderboard();await Send(r);break;}
                    case "CHAT": {if(client==null){await Send(Packet.Reply(req,false,"AUTH_REQUIRED"));break;}if(req.GameId!=null&&games.TryGetValue(req.GameId,out var game)){var msg=new Packet{Type="CHAT_MESSAGE",Username=client.Name,Text=(req.Text??"")[..Math.Min((req.Text??"").Length,500)],GameId=game.Id};await SaveChat(game.Id,client.Name,msg.Text??"");await game.White.Send(msg);await game.Black.Send(msg);}else{foreach(var c in online.Values)await c.Send(new Packet{Type="CHAT_MESSAGE",Username=client.Name,Text=(req.Text??"")[..Math.Min((req.Text??"").Length,500)]});}break;}
                    case "DRAW_REQUEST": case "DRAW_RESPONSE": case "RESIGN": {if(FindGame(req,client,out var g)){var other=client==g.White?g.Black:g.White;if(req.Type=="DRAW_RESPONSE"&&req.Accept){await FinishGame(g,"Draw");await other.Send(new Packet{Type="GAME_END",Result="Draw"});await client!.Send(new Packet{Type="GAME_END",Result="Draw"});games.TryRemove(g.Id,out _);}else if(req.Type=="DRAW_RESPONSE")await other.Send(new Packet{Type="DRAW_DECLINED",GameId=g.Id});else if(req.Type=="RESIGN"){await FinishGame(g,client==g.White?"Black wins by resignation":"White wins by resignation");await other.Send(new Packet{Type="GAME_END",Result="Opponent resigned"});await client!.Send(new Packet{Type="GAME_END",Result="You resigned"});games.TryRemove(g.Id,out _);}else await other.Send(new Packet{Type="DRAW_REQUEST",GameId=g.Id,Username=client!.Name});}break;}
                    case "LOGOUT": if(client!=null)online.TryRemove(client.Name,out _);await Send(Packet.Reply(req,true));tcp.Close();return;
                    default: await Send(Packet.Reply(req,false,"UNKNOWN_MESSAGE_TYPE"));break;
                }
            }
        }catch(Exception e){Console.WriteLine($"Client ended: {e.Message}");}
        finally {if(client!=null)online.TryRemove(client.Name,out _);tcp.Close();}
    }
    private bool FindGame(Packet req,Client? c,out Game g){if(c!=null&&req.GameId!=null&&games.TryGetValue(req.GameId,out g!)&&(g.White==c||g.Black==c))return true;g=null!;return false;}
    private static string Hash(string password){var salt=RandomNumberGenerator.GetBytes(16);var key=Rfc2898DeriveBytes.Pbkdf2(password,salt,210_000,HashAlgorithmName.SHA256,32);return Convert.ToHexString(salt)+":"+Convert.ToHexString(key);}
    private static bool Verify(string password,string stored){var parts=stored.Split(':');if(parts.Length!=2)return false;var salt=Convert.FromHexString(parts[0]);var actual=Rfc2898DeriveBytes.Pbkdf2(password,salt,210_000,HashAlgorithmName.SHA256,32);return CryptographicOperations.FixedTimeEquals(actual,Convert.FromHexString(parts[1]));}
    private static DbConnection NewConnection()=> (DbConnection?)Type.GetType("Microsoft.Data.SqlClient.SqlConnection, Microsoft.Data.SqlClient")?.GetConstructor([typeof(string)])?.Invoke([Environment.GetEnvironmentVariable("CHESS_DB")??"Server=localhost\\SQLEXPRESS;Database=OnlineChess;Trusted_Connection=True;TrustServerCertificate=True;"]) ?? throw new InvalidOperationException("SQL Server provider missing. Build with -p:UseSqlClientPackage=true.");
    private async Task InitializeDatabase(){await using var c=NewConnection();await c.OpenAsync();var cmd=c.CreateCommand();cmd.CommandText="IF OBJECT_ID('dbo.Users') IS NULL CREATE TABLE dbo.Users(UserId int IDENTITY PRIMARY KEY, Username nvarchar(32) NOT NULL UNIQUE, PasswordHash nvarchar(128) NOT NULL, DisplayName nvarchar(64) NOT NULL, CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME(), LastLogin datetime2 NULL); IF OBJECT_ID('dbo.Games') IS NULL CREATE TABLE dbo.Games(GameId uniqueidentifier PRIMARY KEY, WhiteUserId int NOT NULL REFERENCES dbo.Users(UserId), BlackUserId int NOT NULL REFERENCES dbo.Users(UserId), StartedAt datetime2 NOT NULL, EndedAt datetime2 NULL, Result nvarchar(24) NULL); IF OBJECT_ID('dbo.Moves') IS NULL CREATE TABLE dbo.Moves(MoveId bigint IDENTITY PRIMARY KEY, GameId uniqueidentifier NOT NULL REFERENCES dbo.Games(GameId), Ply int NOT NULL, FromSquare char(2) NOT NULL, ToSquare char(2) NOT NULL, CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME()); IF OBJECT_ID('dbo.ChatMessages') IS NULL CREATE TABLE dbo.ChatMessages(MessageId bigint IDENTITY PRIMARY KEY, GameId uniqueidentifier NULL, Username nvarchar(32) NOT NULL, Message nvarchar(500) NOT NULL, CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());";await cmd.ExecuteNonQueryAsync();Console.WriteLine("SQL Server database schema ready.");}
    private async Task<bool> RegisterUser(string name,string password,string display){try{await using var c=NewConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText="INSERT dbo.Users(Username,PasswordHash,DisplayName) VALUES(@u,@p,@d)";q.Parameters.AddWithValue("@u",name);q.Parameters.AddWithValue("@p",Hash(password));q.Parameters.AddWithValue("@d",display);await q.ExecuteNonQueryAsync();return true;}catch(DbException e) when(e.Message.Contains("duplicate",StringComparison.OrdinalIgnoreCase)||e.Message.Contains("unique",StringComparison.OrdinalIgnoreCase)){return false;}}
    private async Task<bool> CheckUser(string name,string password){await using var c=NewConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText="SELECT PasswordHash FROM dbo.Users WHERE Username=@u";q.Parameters.AddWithValue("@u",name);var stored=(string?)await q.ExecuteScalarAsync();if(stored==null||!Verify(password,stored))return false;var update=c.CreateCommand();update.CommandText="UPDATE dbo.Users SET LastLogin=SYSUTCDATETIME() WHERE Username=@u";update.Parameters.AddWithValue("@u",name);await update.ExecuteNonQueryAsync();return true;}
    private async Task SaveGame(Game g){await using var c=NewConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText="INSERT dbo.Games(GameId,WhiteUserId,BlackUserId,StartedAt) SELECT @g,w.UserId,b.UserId,SYSUTCDATETIME() FROM dbo.Users w CROSS JOIN dbo.Users b WHERE w.Username=@w AND b.Username=@b";q.Parameters.AddWithValue("@g",Guid.Parse(g.Id));q.Parameters.AddWithValue("@w",g.White.Name);q.Parameters.AddWithValue("@b",g.Black.Name);await q.ExecuteNonQueryAsync();}
    private async Task SaveMove(string id,string from,string to){await using var c=NewConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText="INSERT dbo.Moves(GameId,Ply,FromSquare,ToSquare) SELECT @g,ISNULL(MAX(Ply),0)+1,@f,@t FROM dbo.Moves WHERE GameId=@g";q.Parameters.AddWithValue("@g",Guid.Parse(id));q.Parameters.AddWithValue("@f",from);q.Parameters.AddWithValue("@t",to);await q.ExecuteNonQueryAsync();}
    private async Task SaveChat(string id,string username,string message){await using var c=NewConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText="INSERT dbo.ChatMessages(GameId,Username,Message) VALUES(@g,@u,@m)";q.Parameters.AddWithValue("@g",Guid.Parse(id));q.Parameters.AddWithValue("@u",username);q.Parameters.AddWithValue("@m",message);await q.ExecuteNonQueryAsync();}
    private async Task FinishGame(Game g,string result){await using var c=NewConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText="UPDATE dbo.Games SET EndedAt=SYSUTCDATETIME(),Result=@r WHERE GameId=@g";q.Parameters.AddWithValue("@r",result);q.Parameters.AddWithValue("@g",Guid.Parse(g.Id));await q.ExecuteNonQueryAsync();}
    private async Task<List<string>> History(string username){if(string.IsNullOrEmpty(username))return [];await using var c=NewConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText="SELECT TOP 25 CONVERT(varchar(19),g.StartedAt,120)+' | '+CASE WHEN w.Username=@u THEN b.Username ELSE w.Username END+' | '+COALESCE(g.Result,'In progress') FROM dbo.Games g JOIN dbo.Users w ON w.UserId=g.WhiteUserId JOIN dbo.Users b ON b.UserId=g.BlackUserId WHERE w.Username=@u OR b.Username=@u ORDER BY g.StartedAt DESC";q.Parameters.AddWithValue("@u",username);var rows=new List<string>();await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add(r.GetString(0));return rows;}
    private async Task<List<string>> Leaderboard(){await using var c=NewConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText="SELECT TOP 20 u.Username+' | '+CONVERT(varchar(12),COUNT(g.GameId))+' games' FROM dbo.Users u LEFT JOIN dbo.Games g ON u.UserId=g.WhiteUserId OR u.UserId=g.BlackUserId GROUP BY u.Username ORDER BY COUNT(g.GameId) DESC,u.Username";var rows=new List<string>();await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add(r.GetString(0));return rows;}
    private sealed record Game(string Id,Client White,Client Black){public Board Board{get;}=new();public string? Result{get;set;}}
    private sealed class Client(string name,StreamWriter writer){private readonly SemaphoreSlim gate=new(1,1);public string Name{get;}=name;public async Task Send(Packet p){await gate.WaitAsync();try{await writer.WriteLineAsync(Wire.Encode(p));}catch{}finally{gate.Release();}}}
}

static class DbParameterExtensions
{
    public static DbParameter AddWithValue(this DbParameterCollection parameters,string name,object value)
    {var p=parameters.GetType().GetMethod("AddWithValue",[typeof(string),typeof(object)]);if(p?.Invoke(parameters,[name,value]) is DbParameter result)return result;throw new InvalidOperationException("SQL Server parameter collection is unavailable.");}
}
